server:
  port: 8787
  servlet:
    contextPath: /assets

auth-header-name: eve-state

dbms:
  host: localhost
  port: 9876
  schema: eve_assets
  username: eve
  collation: utf8mb4_general_ci
  collation.binary: utf8mb4_bin

---
spring:
  profiles: default

dbms:
  password: eve

debug: true

---
spring:
  profiles: prod

dbms:
  password: Dr!lb00r

debug: false
