dbms:
  host: localhost
  port: 9876
  schema: eve_universe
  username: eve
  collation: utf8mb4_general_ci
  collation.binary: utf8mb4_bin

server:
  port: 8585
  servlet:
    contextPath: /universe

auth-header-name: eve-state

---
spring:
  profiles: default

dbms:
  password: eve

debug: true

---
spring:
  profiles: prod

dbms:
  password: Dr!lb00r

debug: false
