# Platform configs
spring:
  application:
    name: EVE-crawler
  datasource:
    platform: org.hibernate.dialect.MySQL5Dialect
    url: jdbc:mysql://localhost:9876/batch_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: eve_crawler
    password: SuperSecurePasswordForCrawler
  jpa:
    show-sql: false
  batch:
    initialize-schema: always
    size: 50000

esi:
  retry:
    timer: 10000

---
spring:
  profiles: default

debug: true

logging:
  level:
    root: WARN
    com.ractoc: DEBUG
  pattern.console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

---
spring:
  profiles: prod

debug: false

logging:
  level:
    root: WARN
  file:
    path: /var/log/eve
    name: crawler.log
  pattern.file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
