name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx # (jre, jdk, or jdk+fx) - defaults to jdk:  
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Scope for Maven
      uses: undefinedlabs/scope-for-maven-action@v1
      with:
        # Scope DSN
        dsn: ${{secrets.SCOPE_DSN}}
        run-tests: true # optional - default is 'true'
        command: mvn verify # optional - default is 'mvn verify'
